LOCAL_COUCH="http://paul:password@localhost:5984"
DEV_COUCH="http://rt7 admin:my dog has three heads@192.168.1.254"

#couchapp push app.js http://paul:password@localhost:5984/rt7_backoffice_app

curl -X PUT "$DEV_COUCH/rt7_backoffice_app"
curl -X PUT "$DEV_COUCH/cashout_designs"
curl -X PUT "$DEV_COUCH/cashouts"
curl -X PUT "$DEV_COUCH/transactions_designs"
curl -X PUT "$DEV_COUCH/transactions"
curl -X PUT "$DEV_COUCH/cashedout_transactions"
curl -X PUT "$DEV_COUCH/inventory_changes"
curl -X PUT "$DEV_COUCH/invnetory_changes_designs"
curl -X PUT "$DEV_COUCH/media_stats"
curl -X PUT "$DEV_COUCH/media_stats_designs"
curl -X PUT "$DEV_COUCH/menu_buttons"
curl -X PUT "$DEV_COUCH/stores"
curl -X PUT "$DEV_COUCH/stores_designs"
curl -X PUT "$DEV_COUCH/terminals_rt7"
curl -X PUT "$DEV_COUCH/terminals_designs"
curl -X PUT "$DEV_COUCH/campaigns_designs"
curl -X PUT "$DEV_COUCH/users"
curl -X PUT "$DEV_COUCH/users_designs"
curl -X PUT "$DEV_COUCH/companies"
curl -X PUT "$DEV_COUCH/inv_new"
curl -X PUT "$DEV_COUCH/install_files_rt7"
curl -X PUT "$DEV_COUCH/inventory_rt7"
curl -X PUT "$DEV_COUCH/inventory_review_rt7"
curl -X PUT "$DEV_COUCH/menus_corp"
curl -X PUT "$DEV_COUCH/rewards_rt7"
curl -X PUT "$DEV_COUCH/terminals_corp"
curl -X PUT "$DEV_COUCH/campaigns"
curl -X PUT "$DEV_COUCH/vouchers_rt7"
